In [47]:
import fitz  # this is pymupdf
import pandas as pd

### __Combining the statement__

In [66]:
with fitz.open("account_statement.pdf") as doc:
    text = ""
    for x, page in enumerate(doc):
        text += page.getText()

#Create list from string
data_array = text.split("\n")

#Setting Markers
counter = 0
for x,y in enumerate(data_array):
    if "Page" in data_array[x]:
        counter +=1
        data_array[x] = str(counter)


print("The statement has "+ str(counter) + " pages")

The statement has 4 pages

Deprecation: 'getText' removed from class 'Page' after v1.19.0 - use 'get_text'.

In [140]:
combined_list = []

#Begin
x = 2
combined_list = data_array[data_array.index("Balance (R)")+1:data_array.index(str(x))-1]

#Body
while x <counter:
     x += 1
     if (x < 4):
          combined_list += data_array[data_array.index(str(x))+6:data_array.index(str(x+1))-1]
          
     else :
          break

# Ending    
combined_list += data_array[data_array.index(str(x))+6:data_array.index("End")]

### __Cleaning the list__

In [142]:

# Fix description Error
page1 = combined_list
# Identify if the charcter is a letter
for x ,y in enumerate(page1):

    #Check if the character is alphabet
    if page1[x][:1].isalpha() :
        #print(page1[x])
        #Check if its next character is alaphabet
        if  "." not in page1[x+1]:
            page1[x] = page1[x] +" "+page1[x+1]
            page1[x+1] = ""

# Delete empty spaces
page1 = [x for x in page1 if x]

In [145]:
# Delete Money In Out
page1[3] =""

#Looping through the list
x = 3
while x < len(page1):
    x+= 5
    if (x <len(page1)):
        page1[x]= ""
    else :
        break

page1 = [x for x in page1 if x]

In [147]:
#Posting Date
posting_list = []

#Looping through the list
x = 0
posting_list.append(page1[0])
while x < len(page1):
    x+= 4
    if (x <len(page1)):
        posting_list.append(page1[x])

    else :
        break

In [149]:
# Transaction Date
transaction_list = []

#Looping through the list 
x = 1
transaction_list.append(page1[x])

while x < len(page1):
    x+= 4
    if (x <len(page1)):
        transaction_list.append(page1[x])
    else :
        break

In [151]:
# Description 

#Dealing with the initial element 
description_list = []

#Looping through the list 
x = 2
description_list.append(page1[x])

while x < len(page1):
    x+= 4
    if (x <len(page1)):
        description_list.append(page1[x])
    else :
        break

In [153]:
# Balance List 
#Dealing with the initial element 
balance_list = []

#Looping through the list 
x = 3
balance_list.append(page1[x])

while x < len(page1):
    x+= 4
    if (x <len(page1)):
        balance_list.append(page1[x])
    else :
        break

In [154]:
# Data frame
statement_dictionary = {"Posting Date": posting_list,
                        "Transaction Date":transaction_list, 
                        "Description": description_list,
                        "Balance": balance_list
}

#Create Pandas dataframe
statement_df = pd.DataFrame(statement_dictionary)

In [157]:
statement_df.head(20)

,Posting Date,Transaction Date,Description,Balance
0,29/12/2020,29/12/2020,ATM Declined Withdrawal Fee,51.79
1,31/12/2020,31/12/2020,Interest Received,52.02
2,31/12/2020,31/12/2020,Monthly Account Admin Fee,47.02
3,02/01/2021,02/01/2021,Card Purchase Insufficient Funds Fee,46.62
4,18/01/2021,18/01/2021,Cash Deposit 00e3cash Dep Dnr Mam Dnr Mamelodi...,486.62
5,18/01/2021,18/01/2021,Cash Deposit Fee (Notes),481.34
6,18/01/2021,18/01/2021,Cash Deposit 00e3cash Dep Dnr Mam Dnr Mamelodi...,531.34
7,18/01/2021,18/01/2021,Cash Deposit Fee (Notes),530.74
8,18/01/2021,18/01/2021,SMS Notification Fee,529.54
9,20/01/2021,18/01/2021,Online purchase: Rain Bryanston (Card 5813),50.54
10,21/01/2021,21/01/2021,Payment Received S Assegaai,350.54
11,21/01/2021,21/01/2021,Banking App Payment Hazel,100.54
12,21/01/2021,21/01/2021,Payment Fee,99.54
13,21/01/2021,21/01/2021,SMS Notification Fee,98.74
14,22/01/2021,22/01/2021,ATM Cash Withdrawal Mahube Ser2 Pretoria Gpza,28.74
15,22/01/2021,22/01/2021,ATM Cash Withdrawal Fee,19.74
16,22/01/2021,22/01/2021,SMS Notification Fee,19.34
17,25/01/2021,25/01/2021,Payment Received: Sassa Gp 78799177 Pension 21...,369.34
18,25/01/2021,25/01/2021,SMS Notification Fee,368.14
19,27/01/2021,27/01/2021,Banking App Prepaid Purchase VODACOM,356.14